apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-echo
spec:
  selector:
    matchLabels:
      app: my-echo
  replicas: 2
  template:
    metadata:
      labels:
        app: my-echo
    spec:
      containers:
      - name: my-echo
        image: ysakashita/my-echo:20231108
---
apiVersion: v1
kind: Service
metadata:
  name: my-echo
spec:
  selector:
    app: my-echo
  ports:
  - port: 1323
    targetPort: 1323
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-echo
  labels:
    name: my-echo
spec:
  rules:
  - host: my-echo.127.0.0.1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-echo
            port: 
              number: 1323
