name: build, test and image push containers
on: [pull_request]

jobs:
  build:
    name: build-test-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: go test
      run: |
        make test
    - name: go build
      run: |
        make
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push
      id: build-push
      run: |
        make image-build
        make image-push
